### ISSUE TITLE
OpenGL Shader Compilation: extension 'GL_ARB_conservative_depth' is not supported // Unknown identifier 'depth_greater' in layout

### ISSUE THREAD

**Issue by jkamalu** [NSchertler/GeneralizedMotorcycleGraph#1]
Hi, 

Very cool research project.

I"m running into trouble compiling from source as well as with the precompiled binaries. I built the project for development in Xcode with cmake (copying the OpenMesh library and tools .dylib symlinks proved troublesome but I dealt with them manually).

Now, I can compile the project, but the OpenGL shader compilation does not complete successfully. I had gotten the version 330 compatibility errors previously (removing the compatibility seems to have cleared them up), but now I run into a issue with depth_greater. Would you happen to have any idea why this is? Thanks!

`Warning: Could not set english locale.
2018-12-10 18:25:48.892488+0100 RegularMeshTexturing[20110:708873] [General] ERROR: Setting <GLFWContentView: 0x600003500c60> as the first responder for window <GLFWWindow: 0x600003e05300>, but it is in a different window ((null))! This would eventually crash when the view is freed. The first responder will be set to nil.
(
	0   AppKit                              0x00007fff413b6a8b -[NSWindow _validateFirstResponder:] + 530
	1   AppKit                              0x00007fff413b6835 -[NSWindow _setFirstResponder:] + 31
	2   AppKit                              0x00007fff41489114 -[NSWindow _realMakeFirstResponder:] + 448
	3   RegularMeshTexturing                0x00000001003b6b3a createWindow + 1034
	4   RegularMeshTexturing                0x00000001003b64ef _glfwPlatformCreateWindow + 63
	5   RegularMeshTexturing                0x00000001003aef1a glfwCreateWindow + 874
	6   RegularMeshTexturing                0x000000010031a151 _ZN7nanogui6ScreenC2ERKN5Eigen6MatrixIiLi2ELi1ELi0ELi2ELi1EEERKNSt3__112basic_stringIcNS6_11char_traitsIcEENS6_9allocatorIcEEEEbbiiiiijj + 1889
	7   RegularMeshTexturing                0x0000000100287823 _ZN3nse3gui14AbstractViewerC2ERKNSt3__112basic_stringIcNS2_11char_traitsIcEENS2_9allocatorIcEEEEiii + 147
	8   RegularMeshTexturing                0x000000010022a759 _ZN6ViewerC2Ev + 217
	9   RegularMeshTexturing                0x0000000100232075 _ZN6ViewerC1Ev + 21
	10  RegularMeshTexturing                0x00000001002777d6 main + 710
	11  libdyld.dylib                       0x00007fff70fc408d start + 1
)
Error while compiling fragment shader "Cylinder Shader":
#version 330
#extension GL_ARB_conservative_depth: enable

in fData
{
	vec2 cameraInGlyphSpace;
	vec3 posInGlyphSpace;
	float halfHeight;
	vec3 cylinderCenter;
	mat3 glyphSpaceToWorldSpace;
} frag;

uniform float radius;

uniform mat4 mvp;

out vec4 result;
layout (depth_greater) out float gl_FragDepth;

uniform vec4 color;
uniform bool shaded;

void main()
{
	vec3 camPos = vec3(frag.cameraInGlyphSpace, 0);
	vec3 dir = frag.posInGlyphSpace - camPos;
	//quadratic equation
	float a = dir.y * dir.y + dir.z * dir.z;
	float b = 2 * frag.cameraInGlyphSpace.y * dir.y;
	float c = frag.cameraInGlyphSpace.y * frag.cameraInGlyphSpace.y - radius * radius;

	b /= a;
	c /= a;

	float discriminant = 0.25 * b * b - c;
	if(discriminant < 0)
		discard;

	float t = -b / 2 - sqrt(discriminant);

	vec3 intersectionPos = camPos + t * dir;
	if(intersectionPos.x < -frag.halfHeight || intersectionPos.x > frag.halfHeight)
		discard;
	
		vec3 normal = intersectionPos;
		normal.x = 0;
		normal = normalize(normal);
		dir = normalize(dir);

		vec4 proj = mvp * vec4(frag.glyphSpaceToWorldSpace * intersectionPos + frag.cylinderCenter, 1);
		gl_FragDepth = ((gl_DepthRange.diff * proj.z / proj.w) + gl_DepthRange.near + gl_DepthRange.far) / 2.0;

	if(shaded)
	{
		float nDotL = dot(-dir, normal);
		vec3 col = color.rgb * nDotL + vec3(0.5, 0.5, 0.5) * pow(nDotL, 120);

		result = vec4(col, color.a);
	}
	else
		result = color;
}

Error: 
WARNING: 0:2: extension 'GL_ARB_conservative_depth' is not supported
ERROR: 0:18: Unknown identifier 'depth_greater' in layout

libc++abi.dylib: terminating with uncaught exception of type std::runtime_error: Shader compilation failed!
(lldb) `

**Comment by NSchertler** [comment]
Hi, thank you a lot for your feedback. Unfortunately, I was not able to test the application on mac. So, thanks for trying. 
It seems your graphics driver does not support the GL_ARB_conservative_depth extension. Are you using the graphics vendor's driver? Then I would be really surprised if this was not supported. After all, the OpenGL wiki says "Most 3.3 hardware will provide these, given recent drivers" (https://www.khronos.org/opengl/wiki/OpenGL_Extension). You could try to update your graphics driver and see if this resolves the problem.
If not, then you can just remove the extension. This will make rendering a bit slower, but it will not change functionality. To do this, remove the line `#extension GL_ARB_conservative_depth: enable` and remove the layout qualifier to make the line with the out variable simply `out float gl_FragDepth;`.
Could you check if this resolves the problem?
Btw, there should be no copying necessary if you use the provided submodules.

**Comment by jkamalu** [comment]
Hi Nico, thanks a lot for your quick reply. I’ll look into what you
suggested the next chance I get and let you know if it’s resolved.

Le lun. 10 déc. 2018 à 18:41, Nico Schertler <notifications@github.com> a
écrit :

**Comment by jkamalu** [comment]
Alright, I've just run through the suggestions you've made.

1. Out of the box, I don't think it's possible for me to _not_ use the graphics vendor drivers with macOS. Updating, unless I am missing something, would also be out of the question, although apparently my graphics hardware supports past 3.3 through 4.1.

2. I removed the line and the layout specification, but then oddly, just redeclaring `out float gl_FragDepth` led to an error even though original behavior is not changed. ERROR: 0:1: Regular non-array variable 'gl_FragDepth' may not be redeclared. Removing this line altogether suppressed the error (I'm not too versed in OpenGL, so forgive me if this had some other consequence).

3. All the while, this error is generated, and after removing the troublesome line in (2), produces an error.

`RegularMeshTexturing[22586:770506] [General] ERROR: Setting <GLFWContentView: 0x60000350e9f0> as the first responder for window <GLFWWindow: 0x600003e02600>, but it is in a different window ((null))! This would eventually crash when the view is freed. The first responder will be set to nil.`

I try to remedy this by making the edit to cocoa_window.m found here (https://github.com/glfw/glfw/pull/883/files) but then end up with a null pointer error and no stack trace.

All of this really touches this project fairly tangentially, esp. if it wasn't tested or built to run on macOS (and what's more as of very recently w/ macOS 10.14 OpenGL has been deprecated), so though I would appreciate any hints as to where you think something isn't quite right, I understand if it's out of scope!

**Comment by NSchertler** [comment]
I am sorry that you are having so much trouble. You are right about the gl_FragDepth - this line should just be removed.
I am a bit lost about the glfw error, though - mostly because I don't have any experience with macOS development. The main question is if this is a general problem or specific to this project. Could you try another project that runs with nanogui (e.g. my [Online Surface Reconstruction](https://github.com/NSchertler/OnlineSurfaceReconstruction) (pre-compiled binaries should be sufficient) or the [nanoGUI examples](https://github.com/wjakob/nanogui))? If they all have the same problem, I would advice to post an issue in the nanoGUI project. Wenzel has much more experience with macOS than I have. If other projects work just fine, the problem must be somewhere in my code.

**Comment by jkamalu** [comment]
Hello again -- I am happy to report that your Online Surface Reconstruction precompile macOS binaries work just fine! The program was unable to find the .dylib libraries at first, but this was temporarily fixed by setting $DYLD_FALLBACK_LIBRARY_PATH to the unzip directory containing all .dylib files and the unix executable.

Does this mean there is a fundamental difference in the way windows are created across projects? 

Also, because we're talking about the binaries, attempting to run the GMG binary, I run into the #version 330 compatibility issues that you'd dealt with in other projects' code.

**Comment by NSchertler** [comment]
Hm.. very interesting. I might have an idea what the problem could be. GMCG references nanogui commit  d0f177e  (Mar 21, 2018). OSR references the newer commit 97b1526 (May 29). I don't see anything relevant in the excluded commits, but it might be worth a try. Could you please update the nanogui submodule to the latest commit and check if this resolves the problem?

**Comment by jkamalu** [comment]
Unfortunately, checking out commit 97b1526 doesn't fix the problem. Any other thoughts or intuitions ?

**Comment by NSchertler** [comment]
I fear I am out of ideas then since both projects use pretty much the same setup. Have you included the `NANOGUI_USE_GLAD=ON` option in CMake? That might be the only difference (the pre-compiled binaries are built with this option).
Assuming this is not the problem, all you could do is step through the code and check when the error occurs. Since OSR is running, you could do a side-by-side comparison of the used code branches. I am sorry that I can't be of more help here. This is pretty hard to debug without a Mac in front of you...
