### ISSUE TITLE
Shader error running on Mac OS

### ISSUE THREAD

**Issue by kabukunz** [NSchertler/GeneralizedMotorcycleGraph#3]
Hello there, I'd like to test the app but I receive a lot of errors on shaders while running, both on prebuilt binaries and sources...

```
Warning: Could not set english locale.
Error while compiling geometry shader "FlatMeshShader":
#version 330 compatibility

/*
	This file is part of the implementation for the technical paper

		Field-Aligned Online Surface Reconstruction
		Nico Schertler, Marco Tarini, Wenzel Jakob, Misha Kazhdan, Stefan Gumhold, Daniele Panozzo
		ACM TOG 36, 4, July 2017 (Proceedings of SIGGRAPH 2017)

	Use of this source code is granted via a BSD-style license, which can be found
	in License.txt in the repository root.

	@author Nico Schertler
*/

layout(triangles) in;
layout(triangle_strip, max_vertices = 3) out;

in GEOM_IN
{
	vec4 pos;
	vec4 color;	
} vIn[];

out FRAG_IN
{
	vec4 pos;
	vec4 color;	
	vec3 n;
} vOut;

void main(void)
{
	vOut.n = normalize(cross(vIn[1].pos.xyz - vIn[0].pos.xyz, vIn[2].pos.xyz - vIn[0].pos.xyz));
	for(int i = 0; i < 3; ++i)
	{
		vOut.pos = vIn[i].pos;
		vOut.color = vIn[i].color;
		gl_Position = gl_in[i].gl_Position;
		EmitVertex();
	}
}

Error: 
ERROR: 0:1: '' : syntax error: #version

libc++abi.dylib: terminating with uncaught exception of type std::runtime_error: Shader compilation failed!
Abort trap: 6

```

The app builds correctly. I'm on Mac Os Mojave 10.14.3

**Comment by NSchertler** [comment]
Can you please check if that solved the problem?

**Comment by kabukunz** [comment]
That made a step forward. Now the error is different:

```
max:MacOS ./RegularMeshTexturing 
Warning: Could not set english locale.
Error while compiling fragment shader "Cylinder Shader":
#version 330
#extension GL_ARB_conservative_depth: enable

in fData
{
	vec2 cameraInGlyphSpace;
	vec3 posInGlyphSpace;
	float halfHeight;
	vec3 cylinderCenter;
	mat3 glyphSpaceToWorldSpace;
} frag;

uniform float radius;

uniform mat4 mvp;

out vec4 result;
layout (depth_greater) out float gl_FragDepth;

uniform vec4 color;
uniform bool shaded;

void main()
{
	vec3 camPos = vec3(frag.cameraInGlyphSpace, 0);
	vec3 dir = frag.posInGlyphSpace - camPos;
	//quadratic equation
	float a = dir.y * dir.y + dir.z * dir.z;
	float b = 2 * frag.cameraInGlyphSpace.y * dir.y;
	float c = frag.cameraInGlyphSpace.y * frag.cameraInGlyphSpace.y - radius * radius;

	b /= a;
	c /= a;

	float discriminant = 0.25 * b * b - c;
	if(discriminant < 0)
		discard;

	float t = -b / 2 - sqrt(discriminant);

	vec3 intersectionPos = camPos + t * dir;
	if(intersectionPos.x < -frag.halfHeight || intersectionPos.x > frag.halfHeight)
		discard;
	
		vec3 normal = intersectionPos;
		normal.x = 0;
		normal = normalize(normal);
		dir = normalize(dir);

		vec4 proj = mvp * vec4(frag.glyphSpaceToWorldSpace * intersectionPos + frag.cylinderCenter, 1);
		gl_FragDepth = ((gl_DepthRange.diff * proj.z / proj.w) + gl_DepthRange.near + gl_DepthRange.far) / 2.0;

	if(shaded)
	{
		float nDotL = dot(-dir, normal);
		vec3 col = color.rgb * nDotL + vec3(0.5, 0.5, 0.5) * pow(nDotL, 120);

		result = vec4(col, color.a);
	}
	else
		result = color;
}

Error: 
WARNING: 0:2: extension 'GL_ARB_conservative_depth' is not supported
ERROR: 0:18: Unknown identifier 'depth_greater' in layout

libc++abi.dylib: terminating with uncaught exception of type std::runtime_error: Shader compilation failed!
Abort trap: 6


```

I'm not using binaries, I've recompiled from sources.
HTH

**Comment by NSchertler** [comment]
That means that your graphics driver does not support conservative depth. That should be no problem - you just need to remove the corresponding code pieces (all in `cylinder.frag`):

line 2: `#extension GL_ARB_conservative_depth: enable` (remove completely)
line 18: remove `layout (depth_greater)`

**Comment by kabukunz** [comment]
OK. Now I get a redeclared variable:

max:MacOS ./RegularMeshTexturing 
Warning: Could not set english locale.
Error while compiling fragment shader "Cylinder Shader":
#version 330


in fData
{
	vec2 cameraInGlyphSpace;
	vec3 posInGlyphSpace;
	float halfHeight;
	vec3 cylinderCenter;
	mat3 glyphSpaceToWorldSpace;
} frag;

uniform float radius;

uniform mat4 mvp;

out vec4 result;
out float gl_FragDepth;

uniform vec4 color;
uniform bool shaded;

void main()
{
	vec3 camPos = vec3(frag.cameraInGlyphSpace, 0);
	vec3 dir = frag.posInGlyphSpace - camPos;
	//quadratic equation
	float a = dir.y * dir.y + dir.z * dir.z;
	float b = 2 * frag.cameraInGlyphSpace.y * dir.y;
	float c = frag.cameraInGlyphSpace.y * frag.cameraInGlyphSpace.y - radius * radius;

	b /= a;
	c /= a;

	float discriminant = 0.25 * b * b - c;
	if(discriminant < 0)
		discard;

	float t = -b / 2 - sqrt(discriminant);

	vec3 intersectionPos = camPos + t * dir;
	if(intersectionPos.x < -frag.halfHeight || intersectionPos.x > frag.halfHeight)
		discard;
	
		vec3 normal = intersectionPos;
		normal.x = 0;
		normal = normalize(normal);
		dir = normalize(dir);

		vec4 proj = mvp * vec4(frag.glyphSpaceToWorldSpace * intersectionPos + frag.cylinderCenter, 1);
		gl_FragDepth = ((gl_DepthRange.diff * proj.z / proj.w) + gl_DepthRange.near + gl_DepthRange.far) / 2.0;

	if(shaded)
	{
		float nDotL = dot(-dir, normal);
		vec3 col = color.rgb * nDotL + vec3(0.5, 0.5, 0.5) * pow(nDotL, 120);

		result = vec4(col, color.a);
	}
	else
		result = color;
}

Error: 
ERROR: 0:18: Regular non-array variable 'gl_FragDepth' may not be redeclared

libc++abi.dylib: terminating with uncaught exception of type std::runtime_error: Shader compilation failed!
Abort trap: 6

**Comment by kabukunz** [comment]
I think you can let go of this. I've used the windows precompiled, and it worked. I don't know if you want to check some more for the sake of bug squashing, anyway... Apple deprecated OpenGL so those bugs are going to became more and more common...
